### ISSUE TITLE
Will you update to 1.21

### ISSUE THREAD

**Issue by FallingUser** [DuncanRuns/Title-Fix-Mod#2]
Not to rush or anything, but is there a plan to update this mod to 1.21 and if so, do you have an ETA?

It's not meant to rush you but more so for me to know if I should keep an eye out on this mod.

**Comment by FallingUser** [comment]
What have you been up to? Why haven't you heard anything?
If you don't hear anything in 3 days, I'll fork your package and upgrade the mod myself.
@DuncanRuns

**Comment by DuncanRuns** [comment]
you can use https://modrinth.com/mod/debugify if you are desperate for this fix

**Comment by DuncanRuns** [comment]
https://modrinth.com/mod/title-fix-mod/version/LR1jneCC
